FROM node:11.1

MAINTAINER abgata20000

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

WORKDIR /root

ARG CMD_YARN_VERSION=1.13.0
RUN npm install --global yarn@$CMD_YARN_VERSION && \
    chmod +x /usr/local/bin/yarn

WORKDIR /myapp
COPY package.json yarn.lock /myapp/
RUN yarn install

COPY . /myapp
