version: '3'
services:
  web:
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    image: web_image
    command: yarn dev
    env_file:
      - "./.env.docker.dev"
    volumes:
      - .:/myapp:cached
      - node_modules:/myapp/node_modules:delegated
    ports:
      - "3333:3333"
    tty: true
    stdin_open: true
volumes:
  node_modules:

